project:
  type: website

website:
  title: "Jon Skogland"
  site-url: "https://jonskogland.com"
  navbar:
    left:
      - href: index.qmd
        text: Posts
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



