project:
  type: website

website:
  title: "Jon Skogland"
  site-url: "https://jonskogland.com"
  navbar:
    left:
      - href: posts.qmd
        text: Posts
      - href: pdfs/Online_CV.pdf
        text: CV
  search: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    respect-user-color-scheme: true



